---
name: "Docker Image Cache"
description: "Pulls a docker image cache for the given image:tag."

inputs:
  image_name:
    description: "Docker image name to pull"
    required: true
  tag_name:
    description: "Docker image tag to pull"
    required: false
    default: "latest"
  registry: # registry containing the image
    description: "docker registry for image (all lower case, end in '/')
                  for registry.hub.docker.com used a blank string"
    required: false
    default: "docker.pkg.github.com/$GITHUB_REPOSITORY"
  expiry: # Number of days to keep cache
    description: "Number of days before the cache is rebuilt"
    required: false
    default: "3"

outputs:
  setting:
    description: "Docker Cache setting for use in docker build."
    value: ${{ steps.cache.outputs.setting }}
  cache_tag:
    description: "Docker tag of the cached image"
    value: ${{ steps.cache.outputs.cache_tag }}

runs:
  using: "composite"
  steps:
    - name: Pull cache layers (if any)
      id: cache
      shell: bash
      run: |
        export EXPIRY_TIME_IN_DAYS=${{ inputs.expiry }}
        ./Docker_Image_Cache/prepare_container_image_cache.sh \
          "${{ inputs.registry }}${{ inputs.image_name }}" \
          "${{ inputs.tag_name }}"