---
name: "Promote Branch"
description: "Promote a branch to a release branch"

inputs:
  from_branch:  # name of from_branch branch
    description: "branch to promote"
    required: false
    default: "devel" # Should this be master,main
  release_branch:  # name of release branch
    description: "branch to promote/merge to"
    required: false
    default: "main"
  tag_prefix: # Git tag prefix
    description: "Any prefix for the tag bump"
    required: false
    default: ""
  github_token: # secret github token
    description: "github token eg. ${{ secrets.GITHUB_TOKEN }}"
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}

runs:
  using: "composite"
  steps:
    - name: Debug
      id: debug
      run: |
        echo "###################################"
        echo "Promote Inputs:"
        echo "---"
        echo "from_branch=${{ inputs.from_branch }}"
        echo "release_branch=${{ inputs.release_branch }}"
        echo "tag_prefix=${{ inputs.tag_prefix }}"
        echo "github_token=${{ inputs.github_token }}"
        echo "---"

    - name: Merge to master
      id: merge
      if: env.ACT != 'true'
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: ${{ inputs.from_branch }}
        target_branch: ${{ inputs.release_branch }}
        github_token: ${{ inputs.github_token }}

    - name: Normalise tag to semantic-release
      if: env.ACT != 'true'
      uses: MasterOfMalt/Atom.DevOps.GitHubActions/Git_Normalise_Tag@PLOPS-427_initial_draft

    - name: Bump version and push tag
      if: env.ACT != 'true'
      id: version_bump
      uses: mathieudutour/github-tag-action@v5.3
      with:
        release_branches: master,main
        tag_prefix: ''
        github_token: ${{ inputs.github_token }}

# TODO: How should we handle create releases?
#      - name: Create a GitHub release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ steps.tag_version.outputs.new_tag }}
#          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}