---
name: "Docker Image Cache"
description: "Pulls a docker image cache for the given image:tag."

inputs:
  image_name:
    description: "Docker image name to pull"
    required: true
  new_tag_name:
    description: "New docker image tag to pull"
    required: true
  registry: # registry containing the image
    description: "docker registry for image (all lower case, end in '/')
                  for registry.hub.docker.com used a blank string"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.registry }}${{ inputs.image_name }}
    - ${{ inputs.new_tag_name }}
