---
name: "Docker Image Get Tag"
description: "Use the GitHub refs to determine the tag for a docker image."

outputs:
  tag_name:
    description: "tag to use for the docker image"
    value: ${{ steps.get_tag.outputs.tag_name }}

runs:
  using: "composite"
  steps:
    - name: Determine tag
      id: get_tag
      shell: bash
      run: |
        ./Docker_Image_GetTag/get_git_tag.sh
