name: "CI"
on:
  push:
    branches:
      - master
      - devel
  pull_request:

env:
  REGISTRY: docker.pkg.github.com
  IMAGE_REPO: docker.pkg.github.com/masterofmalt/atom.devops.githubactions/

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: "Test"
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - uses: ./Docker_Image_GetTag
        id: get_tag

      - name: Check Return Tag
        run: |
          if [ "${{ steps.get_tag.outputs.tag_name }}" == "" ]; then
            exit 1
          fi

      - name: Login to registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./Docker_Build_From_Cache
        id: build_from_cache
        with:
          dockerfile: ./.github/Dockerfile
          image_prefix: test_image_name_
          pull_tag_name: ${{ steps.get_tag.outputs.tag_name }}
          registry: ${{ env.IMAGE_REPO }}
          image_targets: "base,runner"

      - name: Check Cache Outputs
        run: |
          set -x
          if [ "${{ steps.build_from_cache.outputs.image_name_tags }}" != "${{ env.IMAGE_REPO }}test_image_name_base:${{ steps.get_tag.outputs.tag_name }},${{ env.IMAGE_REPO }}test_image_name_base:${{ steps.get_tag.outputs.tag_name }}" ]; then
            exit 1
          fi

      - name: push_tagged_targets
        run: |
          # For this tests purpose we need to add the latest tag too. In the real world this
          # is done during a devel merge by GetTag retrieving 'latest'
          for image in
          docker tag \
            "${IMAGE_REPO}test_image_name:${{ steps.get_tag.outputs.tag_name }}" \
            "${IMAGE_REPO}test_image_name:latest"
          docker push "${IMAGE_REPO}test_image_name:latest"
          docker push "${IMAGE_REPO}test_image_name:${{ steps.get_tag.outputs.tag_name }}"

      - uses: ./Docker_Image_Cache
        id: nocache
        with:
          image_name: test_image_name
          tag_name: NotATag
          registry: ${{ env.IMAGE_REPO }}

      - name: Check Cache Outputs
        run: |
          if [ "${{ steps.nocache.outputs.setting }}" != "--no-cache" ]; then
            exit 1
          fi

      - uses: ./Docker_Image_Cache
        id: cache
        with:
          image_name: ubuntu
          tag_name: latest
          registry: ""

      - name: Check Cache Outputs
        run: |
          if [ "${{ steps.cache.outputs.setting }}" != "--no-cache" ]; then
            exit 1
          fi

      - uses: ./Docker_Image_Build
        id: build
        with:
          dockerfile: ./.github/Dockerfile
          image_name: test_image_name
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          registry: ${{ env.IMAGE_REPO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cache_setting: ${{ steps.cache.outputs.setting }}

      - name: Check Image Build
        env:
          check_value: ${{ env.IMAGE_REPO }}test_image_name:${{ steps.get_tag.outputs.tag_name }}
        run: |
          if [ "${{ steps.build.outputs.image_name_tag }}" != "${{ env.check_value }}" ]; then
            exit 1
          fi

      - name: push
        run: |
          # For this tests purpose we need to add the latest tag too. In the real world this
          # is done during a devel merge by GetTag retrieving 'latest'
          docker tag \
            "${IMAGE_REPO}test_image_name:${{ steps.get_tag.outputs.tag_name }}" \
            "${IMAGE_REPO}test_image_name:latest"
          docker push "${IMAGE_REPO}test_image_name:latest"
          docker push "${IMAGE_REPO}test_image_name:${{ steps.get_tag.outputs.tag_name }}"

      - uses: ./Docker_Image_SetTag
        id: tag_image
        with:
          image_name: test_image_name
          new_tag_name: ${{ steps.get_tag.outputs.tag_name }}
          registry: ${{ env.IMAGE_REPO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Image Tag
        run: |
          if ! docker images | \
                grep "${IMAGE_REPO}test_image_name" | \
                grep "${{ steps.get_tag.outputs.tag_name }}"; then
            exit 1
          fi

      - name: Normalise tag to semantic-release
        if: env.ACT != 'true'
        uses: ./Git_Normalise_Tag
        id: normalise_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Git Tag
        run: |
          if [ "${{ steps.normalise_tag.outputs.new_git_tag }}" != "" ] &&
            ! git tag | grep "${{ steps.normalise_tag.outputs.new_git_tag }}"; then
            exit 1
          fi

  promote:
    if: github.ref == 'refs/heads/devel'
    name: "Promote"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Merge to master
        id: merge
        if: env.ACT != 'true'
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: devel
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalise tag to semantic-release
        if: env.ACT != 'true'
        uses: ./Git_Normalise_Tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        if: env.ACT != 'true'
        id: version_bump
        uses: mathieudutour/github-tag-action@v5.3
        with:
          release_branches: master,main,devel
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.new_tag }}
          release_name: Release ${{ steps.version_bump.outputs.new_tag }}
          body: ${{ steps.version_bump.outputs.changelog }}